#!/usr/bin/env python3
"""
Aggregate all completed prospect analyses into a ranked dashboard.

Reads every results/*/prospect-data.json, produces:
  - PROSPECTS-DASHBOARD.md  (human-readable leaderboard)
  - results/dashboard.csv   (spreadsheet-ready, all fields)

Usage:
    python scripts/aggregate.py
"""

import csv
import json
from datetime import datetime
from pathlib import Path

BASE_DIR       = Path(__file__).parent.parent
RESULTS        = BASE_DIR / "results"
DASHBOARD_MD   = BASE_DIR / "PROSPECTS-DASHBOARD.md"
DASHBOARD_CSV  = RESULTS / "dashboard.csv"


def load_all() -> list[dict]:
    companies = []
    for p in sorted(RESULTS.glob("*/prospect-data.json")):
        try:
            d = json.loads(p.read_text(encoding="utf-8"))
            d["_folder"] = str(p.parent)
            companies.append(d)
        except Exception as e:
            print(f"[WARN] Could not load {p}: {e}")

    companies.sort(key=lambda x: float(x.get("prospect_score") or 0), reverse=True)
    return companies


def _grade_emoji(grade: str) -> str:
    return {"A+": "🔥", "A": "✅", "B": "🔵", "C": "🟡", "D": "🔴"}.get(grade, "⚪")


def _dm_name(d: dict) -> str:
    dm = d.get("key_decision_maker", {})
    return dm.get("name", "—") if isinstance(dm, dict) else "—"


def _score(d: dict) -> float:
    try:
        return float(d.get("prospect_score") or 0)
    except (TypeError, ValueError):
        return 0.0


def build_markdown(companies: list[dict]) -> str:
    today  = datetime.now().strftime("%Y-%m-%d")
    scores = [_score(c) for c in companies]
    avg    = round(sum(scores) / len(scores), 1) if scores else 0
    hot    = sum(1 for s in scores if s >= 75)
    qual   = sum(1 for s in scores if 60 <= s < 75)
    cold   = sum(1 for s in scores if s < 60)

    lines = [
        "# Prospects Dashboard",
        f"**Last updated:** {today}  |  **Analyzed:** {len(companies)}  |  "
        f"**Avg score:** {avg}/100  |  **Hot leads:** {hot}",
        "",
        "---",
        "",
        "## Leaderboard",
        "",
        "| # | Company | Score | Grade | Industry | Key DM | Recommended Action |",
        "|---|---------|------:|-------|----------|--------|-------------------|",
    ]

    for i, c in enumerate(companies, 1):
        grade   = c.get("grade", "?")
        emoji   = _grade_emoji(grade)
        company = c.get("company_name", "Unknown")
        sc      = c.get("prospect_score", "?")
        industry= (c.get("industry") or "—")[:28]
        dm      = _dm_name(c)
        action  = (c.get("recommended_action") or "—")[:55]
        lines.append(f"| {i} | **{company}** | {sc}/100 | {emoji} {grade} | {industry} | {dm} | {action} |")

    # Grade buckets
    buckets: dict[str, list[str]] = {
        "A+ · Hot Leads (90-100)":    [],
        "A · Strong Prospects (75-89)": [],
        "B · Qualified Leads (60-74)": [],
        "C · Lukewarm (40-59)":       [],
        "D · Poor Fit (<40)":         [],
    }
    for c in companies:
        s    = _score(c)
        name = c.get("company_name", "?")
        if s >= 90:   buckets["A+ · Hot Leads (90-100)"].append(name)
        elif s >= 75: buckets["A · Strong Prospects (75-89)"].append(name)
        elif s >= 60: buckets["B · Qualified Leads (60-74)"].append(name)
        elif s >= 40: buckets["C · Lukewarm (40-59)"].append(name)
        else:         buckets["D · Poor Fit (<40)"].append(name)

    lines += ["", "---", "", "## By Grade", ""]
    for bucket, names in buckets.items():
        if names:
            lines.append(f"**{bucket}:** {', '.join(names)}  ")

    lines += [
        "",
        "---",
        "",
        "## Summary Stats",
        "",
        "| Metric | Count |",
        "|--------|------:|",
        f"| Total analyzed | {len(companies)} |",
        f"| Hot leads (A/A+, ≥75) | {hot} |",
        f"| Qualified leads (B, 60-74) | {qual} |",
        f"| Nurture / cold (<60) | {cold} |",
        f"| Average prospect score | {avg} |",
        "",
        "---",
        "",
        f"*Generated by AI Sales Batch Analyzer · {today}*",
    ]

    return "\n".join(lines)


CSV_FIELDS = [
    "rank", "company_name", "url", "prospect_score", "grade", "label",
    "confidence", "industry", "company_type", "founded", "employees",
    "funding", "hq_location",
    "company_fit_score", "contact_access_score", "opportunity_quality_score",
    "competitive_position_score", "outreach_readiness_score",
    "bant_total",
    "key_decision_maker", "dm_email_pattern",
    "recommended_action", "analysis_date", "output_folder",
]


def build_csv_rows(companies: list[dict]) -> list[dict]:
    rows = []
    for i, c in enumerate(companies, 1):
        sc  = c.get("scores", {}) or {}
        bant= c.get("bant",   {}) or {}
        dm  = c.get("key_decision_maker", {}) or {}

        def score_of(key):
            return (sc.get(key) or {}).get("score", "")

        rows.append({
            "rank":                      i,
            "company_name":              c.get("company_name", ""),
            "url":                       c.get("url", ""),
            "prospect_score":            c.get("prospect_score", ""),
            "grade":                     c.get("grade", ""),
            "label":                     c.get("label", ""),
            "confidence":                c.get("confidence", ""),
            "industry":                  c.get("industry", ""),
            "company_type":              c.get("company_type", ""),
            "founded":                   c.get("founded", ""),
            "employees":                 c.get("employees", ""),
            "funding":                   c.get("funding", ""),
            "hq_location":               c.get("hq_location", ""),
            "company_fit_score":         score_of("company_fit"),
            "contact_access_score":      score_of("contact_access"),
            "opportunity_quality_score": score_of("opportunity_quality"),
            "competitive_position_score":score_of("competitive_position"),
            "outreach_readiness_score":  score_of("outreach_readiness"),
            "bant_total":                bant.get("total", ""),
            "key_decision_maker":        dm.get("name",          "") if isinstance(dm, dict) else "",
            "dm_email_pattern":          dm.get("email_pattern", "") if isinstance(dm, dict) else "",
            "recommended_action":        c.get("recommended_action", ""),
            "analysis_date":             c.get("analysis_date", ""),
            "output_folder":             c.get("_folder", ""),
        })
    return rows


def main():
    companies = load_all()

    if not companies:
        print("No completed analyses found in results/*/prospect-data.json")
        print("Run 'python scripts/run_batch.py' first.")
        return

    # Markdown dashboard
    DASHBOARD_MD.write_text(build_markdown(companies), encoding="utf-8")
    print(f"Dashboard:     {DASHBOARD_MD}")

    # CSV export
    RESULTS.mkdir(exist_ok=True)
    rows = build_csv_rows(companies)
    with open(DASHBOARD_CSV, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    print(f"Dashboard CSV: {DASHBOARD_CSV}")

    scores = [_score(c) for c in companies]
    hot    = sum(1 for s in scores if s >= 75)
    avg    = round(sum(scores) / len(scores), 1) if scores else 0
    print(f"\n{len(companies)} companies | avg {avg}/100 | {hot} hot leads (≥75)")


if __name__ == "__main__":
    main()
