#!/usr/bin/env python3
"""
Send personalised outreach emails to today's queued prospects.

Reads the queue generated by daily_queue.py, pulls each lead's outreach email
from the DB, sends a plain-text email, then marks the lead as 'sent' in the DB.

Env vars (shared with send_report.py):
    EMAIL_FROM   your Gmail address
    SMTP_USER    same as EMAIL_FROM
    SMTP_PASS    Gmail App Password
    SMTP_HOST    smtp.gmail.com (default)
    SMTP_PORT    587            (default)

Usage:
    python scripts/send_outreach.py              # send today's queue
    python scripts/send_outreach.py --dry-run    # preview without sending
    python scripts/send_outreach.py --date 2026-05-11
"""

import argparse
import json
import os
import smtplib
import sys
import time
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
sys.path.insert(0, str(BASE_DIR))

from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

import db  # noqa: E402


def _smtp_conn():
    host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    port = int(os.environ.get("SMTP_PORT", "587"))
    user = os.environ.get("SMTP_USER") or os.environ.get("EMAIL_FROM", "")
    pwd  = os.environ.get("SMTP_PASS", "")
    server = smtplib.SMTP(host, port)
    server.ehlo()
    server.starttls()
    server.login(user, pwd)
    return server


def build_outreach_email(lead: dict) -> dict | None:
    """Extract validated outreach fields from a lead's analysis_json."""
    raw = lead.get("analysis_json") or ""
    try:
        data = json.loads(raw) if raw else {}
    except Exception:
        data = {}

    email_data = data.get("outreach_email") or {}
    if not isinstance(email_data, dict):
        email_data = {}

    # Merge top-level fields as fallbacks
    dm = data.get("key_decision_maker") or {}
    if not isinstance(dm, dict):
        dm = {}

    to_email = email_data.get("to_email") or dm.get("email_pattern", "")
    to_name  = email_data.get("to_name")  or dm.get("name", "")
    to_title = email_data.get("to_title") or dm.get("title", "")
    subject  = email_data.get("subject_a") or email_data.get("subject", "")
    body     = email_data.get("body", "").strip()
    cta      = email_data.get("cta", "Are you free for a 10-minute call?")

    # Skip if we don't have a real email or a body
    if not to_email or "@" not in to_email or not body:
        return None

    # Append CTA if not already in body
    if cta and cta not in body:
        body = f"{body}\n\n{cta}"

    return {
        "to_email": to_email,
        "to_name":  to_name,
        "to_title": to_title,
        "subject":  subject or f"Quick question about {lead.get('company_name', '')}",
        "body":     body,
        "company":  lead.get("company_name", ""),
        "url":      lead.get("url", ""),
    }


def send_outreach(date_str: str, dry_run: bool = False) -> list[dict]:
    """Send outreach emails for the given date's queue. Returns results list."""
    from_addr = os.environ.get("EMAIL_FROM", "")
    if not from_addr or not os.environ.get("SMTP_PASS"):
        print("ERROR: EMAIL_FROM and SMTP_PASS must be set.")
        return []

    queue_entry = db.get_queue(date_str)
    if not queue_entry:
        print(f"No queue found for {date_str}.")
        return []

    queued_names = set()
    try:
        for row in json.loads(queue_entry["queue_json"] or "[]"):
            queued_names.add(row.get("Company Name", "").strip().lower())
    except Exception:
        pass

    if not queued_names:
        print("Queue is empty.")
        return []

    # Match queued companies to full analyses
    analyses = db.get_analyses()
    targets = [
        a for a in analyses
        if a.get("company_name", "").strip().lower() in queued_names
        and (a.get("outreach_status") or "").lower() not in {"sent", "replied", "converted"}
    ]

    if not targets:
        print("All queued leads already marked as sent, or no analyses matched.")
        return []

    print(f"\nSending outreach to {len(targets)} prospects{' [DRY RUN]' if dry_run else ''}...\n")

    results   = []
    server    = None if dry_run else _smtp_conn()
    from_name = "The SG Daily"

    for lead in targets:
        outreach = build_outreach_email(lead)
        company  = lead.get("company_name", lead.get("url", "?"))

        if not outreach:
            print(f"  [SKIP]  {company} — no valid email or body in analysis")
            results.append({"company": company, "status": "skipped", "reason": "missing email/body"})
            continue

        print(f"  [{'DRY' if dry_run else 'SEND'}]  {company}")
        print(f"          To:      {outreach['to_name']} <{outreach['to_email']}>")
        print(f"          Subject: {outreach['subject']}")
        print(f"          Body:    {outreach['body'][:80].replace(chr(10),' ')}...")

        if dry_run:
            results.append({"company": company, "status": "dry_run", **outreach})
            continue

        try:
            msg = MIMEMultipart("alternative")
            msg["Subject"] = outreach["subject"]
            msg["From"]    = f"{from_name} <{from_addr}>"
            msg["To"]      = (
                f"{outreach['to_name']} <{outreach['to_email']}>"
                if outreach["to_name"] else outreach["to_email"]
            )

            # Plain text part (better deliverability for cold outreach)
            plain = outreach["body"]
            msg.attach(MIMEText(plain, "plain"))

            # Simple HTML version
            html_body = outreach["body"].replace("\n", "<br>")
            html = f"""<html><body style="font-family:Arial,sans-serif;font-size:14px;line-height:1.6;color:#222">
{html_body}
</body></html>"""
            msg.attach(MIMEText(html, "html"))

            server.sendmail(from_addr, outreach["to_email"], msg.as_string())
            db.mark_outreach_sent(lead["url"], "sent")

            print(f"          ✓ Sent")
            results.append({"company": company, "status": "sent", **outreach})

            time.sleep(2)  # rate-limit between sends

        except Exception as e:
            print(f"          ✗ Error: {e}")
            results.append({"company": company, "status": "error", "error": str(e)})

    if server:
        server.quit()

    sent  = sum(1 for r in results if r["status"] == "sent")
    skip  = sum(1 for r in results if r["status"] == "skipped")
    err   = sum(1 for r in results if r["status"] == "error")
    print(f"\nOutreach complete: {sent} sent, {skip} skipped, {err} errors")
    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Send outreach emails to today's queue")
    parser.add_argument("--dry-run", action="store_true", help="Preview without sending")
    parser.add_argument("--date",    default=datetime.now().strftime("%Y-%m-%d"),
                        help="Queue date (default: today)")
    args = parser.parse_args()
    send_outreach(args.date, dry_run=args.dry_run)
